# Generated by Django 4.2.20 on 2025-03-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_toy_alter_feeding_options_alter_feeding_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='toy',
            field=models.ManyToManyField(to='main_app.toy'),
        ),
    ]
